### ISSUE TITLE
This is an awesome plugin but it's time has come..obsidian 1.0 removed it's usefulness.

### ISSUE THREAD

**Issue by cocoonkid** [dvcrn/obsidian-filename-heading-sync#63]
This is an awesome plugin but it's time has come..obsidian 1.0 removed it's usefulness.

So how can I now remove all the headings from all files in the easiest way?

Obsidian 1.0 is now showing the filename as heading natively so I have two headings everywhere :-)

**Comment by dvcrn** [comment]
Markdown documents should semantically have a main heading, and that doesn't change with the new Obsidian 1.0 feature. Especially when using other apps to read those same markdown files it's beneficial to have all of those act on the same file content, instead of application specific UI

Personally I just turned the new Obsidian feature off, but if you really want to remove all your main headings I'd look into tools that can bulk edit an entire folder. On unix you can probably do that with `sed` and a regex rule, something like `s/^\#\ .*$//g` (I haven't tested this so pls don't run it on your database)

**Comment by dvcrn** [comment]
I'm closing this issue because I think it'll stay relevant 😄

**Comment by cocoonkid** [comment]
Alright, understood and thanks :-)
